#include <bits/stdc++.h>

using namespace std;

class Solution {
public:
    int reverseNumber(int x) {
        int reversed = 0;
        while (x > 0) {
            reversed = reversed * 10 + (x % 10);
            x /= 10;
        }
        return reversed;
    }
    int minMirrorPairDistance(vector<int>& nums) {
        // Map to store {target_value : latest_index}
        std::unordered_map<int, int> targetMap;
        
        int min_dist = INT_MAX;

        for (int j = 0; j < nums.size(); ++j) {
            // 1. Check if the current number is a target generated by a previous number
            if (targetMap.find(nums[j]) != targetMap.end()) {
                int current_dist = j - targetMap[nums[j]];
                min_dist = std::min(min_dist, current_dist);
            }

            // 2. Generate the target for future numbers and update the map
            // We always overwrite so that the map holds the largest (latest) index 'i'
            int target = reverseNumber(nums[j]);
            targetMap[target] = j;
        }

        // If min_dist wasn't updated, no mirror pair was found
        return min_dist == INT_MAX ? -1 : min_dist; 
    }
};